Registrar/Models/Department.cs
using System.Collections.Generic;

namespace Registrar.Models
{
  public class Department
  {
    public int DepartmentId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Course> Courses { get; set; }
    public virtual ICollection<Student> Students { get; set; }

    public Department()
    {
      this.Courses = new HashSet<Course>();
      this.Students = new HashSet<Student>();
    }
  }
}

Registrar/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Registrar.Models;

namespace Registrar.Controllers
{
  public class CoursesController : Controller
  {
    private readonly RegistrarContext _db;

    public CoursesController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Courses.ToList());
    }

    public ActionResult Details(int id)
    {
      Course thisCourse = _db.Courses
        .Include(course => course.JoinEntities)
        .ThenInclude(join => join.Student)
        .FirstOrDefault(Course => Course.CourseId == id);
      return View(thisCourse);
    }

    public ActionResult Create()
    {
      ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Course Course)
    {
      _db.Courses.Add(Course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name");
      Course thisCourse = _db.Courses.FirstOrDefault(Course => Course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost]
    public ActionResult Edit(Course Course)
    {
      _db.Entry(Course).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Course thisCourse = _db.Courses.FirstOrDefault(Course => Course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Course thisCourse = _db.Courses.FirstOrDefault(Course => Course.CourseId == id);
      _db.Courses.Remove(thisCourse);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Registrar/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Registrar.Models;

namespace Registrar.Controllers
{
  public class DepartmentsController : Controller
  {
    private readonly RegistrarContext _db;

    public DepartmentsController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Departments.ToList());
    }

    public ActionResult Details(int id)
    {
      Department thisDepartment = _db.Departments
        .Include(department => department.Courses)
        .Include(department => department.Students)
        .FirstOrDefault(department => department.DepartmentId == id);
      return View(thisDepartment);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Department department)
    {
      _db.Departments.Add(department);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      Department thisDepartment = _db.Departments.FirstOrDefault(dept => dept.DepartmentId == id);
      return View(thisDepartment);
    }

    [HttpPost]
    public ActionResult Edit(Department dept)
    {
      _db.Entry(dept).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Department thisDepartment = _db.Departments.FirstOrDefault(dept => dept.DepartmentId == id);
      return View(thisDepartment);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Department thisDepartment = _db.Departments.FirstOrDefault(dept => dept.DepartmentId == id);
      _db.Departments.Remove(thisDepartment);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Registrar/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Registrar.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Registrar.Controllers
{
  public class StudentsController : Controller
  {
    private readonly RegistrarContext _db;

    public StudentsController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Student> model = _db.Students.ToList();
      return View(model);
    }

    public ActionResult Details(int id)
    {
      var thisStudent = _db.Students
        .Include(student => student.JoinEntities)
        .ThenInclude(join => join.Course)
        .FirstOrDefault(Student => Student.StudentId == id);
      return View(thisStudent);
    }

    public ActionResult Create()
    {
      ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Student student)
    {
      _db.Students.Add(student);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "Name");
      Student thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult Edit(Student student)
    {
      _db.Entry(student).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddCourse(int id)
    {
      var thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "Name");
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult AddCourse(Student student, int CourseId)
    {
      bool alreadyExists = _db.CourseStudent.Any(courseStudent => courseStudent.StudentId == student.StudentId && courseStudent.CourseId == CourseId);
      if (CourseId != 0 && !alreadyExists)
      {
        _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
      }
      _db.SaveChanges();
      if (alreadyExists)
      {
        return RedirectToAction("AddCourseError");
      }
      return RedirectToAction("Index");
    }

    public ActionResult AddCourseError()
    {
      return View();
    }

    [HttpPost]
    public ActionResult SwitchCompleted(int joinId)
    {
      var joinEntry = _db.CourseStudent.FirstOrDefault(entry => entry.CourseStudentId == joinId);
      joinEntry.Complete = !joinEntry.Complete;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult CompletedDetails(int id)
    {
      var thisStudent = _db.Students
        .Include(student => student.JoinEntities)
        .ThenInclude(join => join.Course)
        .FirstOrDefault(Student => Student.StudentId == id);
      return View(thisStudent);
    }

    [HttpPost]
    public ActionResult DeleteCourse(int joinId)
    {
      var joinEntry = _db.CourseStudent.FirstOrDefault(entry => entry.CourseStudentId == joinId);
      _db.CourseStudent.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Student thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      return View(thisStudent);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Student thisStudent = _db.Students.FirstOrDefault(student => student.StudentId == id);
      _db.Students.Remove(thisStudent);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Registrar/Views/Departments/Create.cshtml
@model Registrar.Models.Department

<h4>Add a new department</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Add new department" class="btn btn-default" />
}

Registrar/Views/Departments/Delete.cshtml
@model Registrar.Models.Department

<h2>Are you sure you want to delete this department?</h2>

@using (Html.BeginForm())
{
  <button class="btn btn-warning" type="submit">Delete department</button>
}

Registrar/Views/Departments/Details.cshtml
@using Registrar.Models;
@model Registrar.Models.Department

<h2>Department Details</h2>
<h3>Department Name: @Html.DisplayFor(model => model.Name)</h3>

@if (@Model.Courses.Count == 0)
{
  <p>This department has no current courses</p>
}
else
{
  <h4>Courses:</h4>
  <ul>
  @foreach (Course course in Model.Courses)
    {
      <li>@Html.ActionLink($"{@course.CourseNumber}: {@course.Name}", "Details", "Courses", new { id = course.CourseId })</li>
    }
  </ul>
}

@if (@Model.Students.Count == 0)
{
  <p>This department has no current students</p>
}
else
{
  <h4>Students:</h4>
  <ul>
  @foreach (Student student in Model.Students)
    {
      <li>@Html.ActionLink($"{@student.Name}", "Details", "Students", new { id = student.StudentId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Edit department", "Edit", new { id = Model.DepartmentId })</p>
<p>@Html.ActionLink("Delete department", "Delete", new {id = Model.DepartmentId })</p>

Registrar/Views/Departments/Edit.cshtml
@model Registrar.Models.Department

<h4>Edit department</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DepartmentId)
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Edit department" class="btn btn-default" />
}

Registrar/Views/Departments/Index.cshtml
@using Registrar.Models;
@model List<Registrar.Models.Department>

<h1>Departments</h1>
<ul>
  @foreach (Department dept in Model)
  {
    <li>@Html.ActionLink($"{dept.Name}", "Details", new { id = dept.DepartmentId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new department", "Create")</p>